name: workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the Code
        uses: actions/checkout@v2

      # Step 2: Create .env file from GitHub Secrets
      - name: Create .env File
        run: echo "${{ secrets.ENV }}" > .env

      # Step 3: Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/jessie_miniproject:latest .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USER }}/jessie_miniproject:latest

  deploy-to-ec2:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: '${{ secrets.DOCKER_USER }}/jessie_miniproject:latest'
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the Code
        uses: actions/checkout@v2

      # Step 2: Create PEM file for EC2 authentication
      - name: Create PEM File
        run: |
          echo "${{ secrets.EC2_PEM }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      # Step 3: Deploy application to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            # Stop and remove the current container if running
            CONTAINER_ID=\$(sudo docker ps -q --filter "name=jessie_miniproject")
            if [ -n "\$CONTAINER_ID" ]; then
              sudo docker stop \$CONTAINER_ID
              sudo docker rm \$CONTAINER_ID
            fi

            # Clean up dangling Docker images
            sudo docker images -f "dangling=true" -q | xargs -r sudo docker rmi

            # Pull the latest image from Docker Hub
            sudo docker pull $IMAGE_URI

            # Run the new container
            sudo docker run -d --name jessie_miniproject -p 8080:8080 $IMAGE_URI
          EOF

      # Step 4: Clean up PEM file
      - name: Clean up PEM File
        run: rm -f ec2-key.pem