name: jasmine_projectflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v2

      # Create .env file from secret
      - name: Create .env file
        run: echo "${{ secrets.ENV }}" > .env

      # Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/jessie_miniproject:1.0.0 .

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USER }}/jessie_miniproject:1.0.0

  deploy-to-ec2:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: '${{ secrets.DOCKER_USER }}/jessie_miniproject:1.0.0'
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}

    steps:
      # Checkout the code
      - name: Checkout the Code
        uses: actions/checkout@v2

      # Create PEM file from secret
      - name: Create PEM File
        run: |
          echo "${{ secrets.EC2_PEM }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            # Stop and remove the current container if running
            CONTAINER_NAME="jessie_miniproject"
            RUNNING_CONTAINER_ID=\$(sudo docker ps -q --filter "name=\$CONTAINER_NAME")
            if [ -n "\$RUNNING_CONTAINER_ID" ]; then
              echo "Stopping and removing running container..."
              sudo docker stop \$RUNNING_CONTAINER_ID
              sudo docker rm \$RUNNING_CONTAINER_ID
            fi

            # Remove stopped containers with the same name
            STOPPED_CONTAINER_ID=\$(sudo docker ps -a -q --filter "name=\$CONTAINER_NAME")
            if [ -n "\$STOPPED_CONTAINER_ID" ]; then
              echo "Removing stopped container..."
              sudo docker rm \$STOPPED_CONTAINER_ID
            fi

            # Remove containers using the same image
            IMAGE_CONTAINER_IDS=\$(sudo docker ps -a --filter "ancestor=$IMAGE_URI" -q)
            if [ -n "\$IMAGE_CONTAINER_IDS" ]; then
              echo "Removing containers using the same image..."
              echo \$IMAGE_CONTAINER_IDS | xargs -r sudo docker rm
            fi

            # Remove dangling images to free up space
            DANGLING_IMAGE_IDS=\$(sudo docker images -f "dangling=true" -q)
            if [ -n "\$DANGLING_IMAGE_IDS" ]; then
              echo "Removing dangling images..."
              echo \$DANGLING_IMAGE_IDS | xargs -r sudo docker rmi
            fi

            # Pull the latest image from Docker Hub
            echo "Pulling the latest image..."
            sudo docker pull $IMAGE_URI

            # Run the new container
            echo "Running new container..."
            sudo docker run -d --name \$CONTAINER_NAME -p 8080:8080 $IMAGE_URI
          EOF

      # Clean up PEM file
      - name: Clean up PEM File
        run: rm -f ec2-key.pem
